reset;
model antennalinrobust1.mod;
data antenna2.dat;
data errors.dat;
option solver cplex;
solve;
for{i in rings,j in S}{
printf "%f \n",diS[i,j] > diS.csv;
}
for{i in rings,j in P}{
printf "%f \n",diP[i,j] > diP.csv;
}
for{i in P}{
printf "%f \n",P[i] > P.csv;
}
for{i in S}{
printf "%f \n",S[i] > S.csv;
}
for{i in rings}{
printf "%f \n",x[i] > antennarobust1TESTTEST.csv;
}
display erreurdiagramme;
